export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_IN = 'LOGIN_IN';
export const LOGIN_ERROR = 'LOGIN_ERROR';

export const SIGNUP_REQUEST = 'SIGNUP_REQUEST';
export const SIGNIN_UP = 'SIGNIN_UP';
export const SIGNUP_ERROR = 'SIGNUP_ERROR';

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';

export const GETTING_PARTIES = 'GETTING_PARTIES';
export const PARTIES_REQUEST = 'PARTIES_REQUEST';
export const CREATING_PARTY = 'CREATING_PARTY';
export const CREATE_PARTY_REQUEST = 'CREATE_PARTY_REQUEST';
export const DELETING_PARTY = 'DELETING_PARTY';
export const DELETE_PARTY_REQUEST = 'DELETE_PARTY_REQUEST';
export const EDITING_PARTY = 'EDITING_PARTY';
export const EDIT_PARTY_REQUEST = 'EDIT_PARTY_REQUEST';

export const CREATE_PARTY_ERROR = 'CREATE_PARTY_ERROR';
export const FETCH_PARTY_ERROR = 'FETCH_PARTY_ERROR';
export const DELETE_PARTY_ERROR = 'DELETE_PARTY_ERROR';
export const EDIT_PARTY_ERROR = 'EDIT_PARTY_ERROR';
